"""Provider-agnostic data types for the agent loop.

All types are frozen dataclasses for immutability and safety across async code.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


@dataclass(frozen=True, slots=True)
class ToolCall:
    """A tool invocation requested by the LLM.

    Attributes:
        id: Unique identifier for this tool call (provider-assigned).
        name: Tool function name (e.g. ``"resolve_terminology"``).
        arguments: Parsed arguments dict.
    """

    id: str
    name: str
    arguments: dict[str, object]


@dataclass(frozen=True, slots=True)
class ToolResult:
    """The result of executing a tool.

    Attributes:
        tool_call_id: ID of the ``ToolCall`` this result corresponds to.
        content: Textual result (JSON string or human-readable summary).
        is_error: Whether the tool execution failed.
    """

    tool_call_id: str
    content: str
    is_error: bool = False


@dataclass(frozen=True, slots=True)
class Message:
    """A single message in the conversation.

    Attributes:
        role: Message role.
        content: Text content (may be ``None`` for tool-call-only messages).
        tool_calls: Tool calls requested in this message (assistant only).
        tool_call_id: ID linking a tool result to its call (tool role only).
    """

    role: Literal["system", "user", "assistant", "tool"]
    content: str | None = None
    tool_calls: tuple[ToolCall, ...] = ()
    tool_call_id: str | None = None


@dataclass(frozen=True, slots=True)
class TokenUsage:
    """Token usage statistics from a single LLM call.

    Attributes:
        input_tokens: Number of input (prompt) tokens.
        output_tokens: Number of output (completion) tokens.
        cache_creation_input_tokens: Tokens written to cache (Anthropic only).
        cache_read_input_tokens: Tokens read from cache (Anthropic only).
    """

    input_tokens: int = 0
    output_tokens: int = 0
    cache_creation_input_tokens: int = 0
    cache_read_input_tokens: int = 0


@dataclass(frozen=True, slots=True)
class LLMResponse:
    """Parsed response from an LLM provider.

    Attributes:
        content: Text content of the response (``None`` if tool-call only).
        tool_calls: Tool calls requested by the model.
        stop_reason: Why the model stopped generating.
        usage: Token usage for this call.
    """

    content: str | None = None
    tool_calls: tuple[ToolCall, ...] = ()
    stop_reason: str = ""
    usage: TokenUsage = field(default_factory=TokenUsage)


@dataclass(frozen=True, slots=True)
class AgentResult:
    """Final result of running the agent loop.

    Attributes:
        answer: The narrative answer generated by the LLM.
        query: The original user query.
        tool_calls_made: All tool calls made during execution.
        iterations: Number of loop iterations.
        success: Whether the agent produced a valid answer.
        trace_id: Langfuse trace ID (``None`` if tracing disabled).
        trace_url: Direct link to the Langfuse trace (``None`` if tracing disabled).
    """

    answer: str
    query: str
    tool_calls_made: tuple[ToolCall, ...] = ()
    iterations: int = 0
    success: bool = True
    trace_id: str | None = None
    trace_url: str | None = None
