"""SaludAI Core — FHIR client, terminology resolver, and shared types."""

from __future__ import annotations

__version__ = "0.1.0"

from saludai_core.config import FHIRConfig
from saludai_core.exceptions import (
    FHIRAuthenticationError,
    FHIRConnectionError,
    FHIRError,
    FHIRResourceNotFoundError,
    FHIRValidationError,
    LocaleNotFoundError,
    QueryBuilderError,
    QueryBuilderValidationError,
    SaludAIError,
    TerminologyCodeNotFoundError,
    TerminologyDataError,
    TerminologyError,
)
from saludai_core.fhir_client import FHIRClient
from saludai_core.locales import (
    CustomOperationDef,
    CustomSearchParamDef,
    ExtensionDef,
    FHIRProfileDef,
    IdentifierSystemDef,
    LocalePack,
    LocaleResourceConfig,
    TerminologySystemDef,
    available_locales,
    build_fhir_awareness_section,
    load_locale_pack,
)
from saludai_core.query_builder import (
    CIE_10_SYSTEM,
    LOINC_SYSTEM,
    SNOMED_CT_SYSTEM,
    DateParam,
    DatePrefix,
    FHIRQuery,
    FHIRQueryBuilder,
    FHIRResourceType,
    IncludeParam,
    QuantityParam,
    ReferenceParam,
    SortOrder,
    SortParam,
    StringParam,
    SummaryMode,
    TokenParam,
    cie10,
    date_param,
    loinc,
    quantity,
    reference,
    snomed,
    token,
)
from saludai_core.terminology import (
    MatchType,
    TerminologyConcept,
    TerminologyConfig,
    TerminologyMatch,
    TerminologyResolver,
    TerminologySystem,
)

__all__ = [
    "CIE_10_SYSTEM",
    "LOINC_SYSTEM",
    "SNOMED_CT_SYSTEM",
    "CustomOperationDef",
    "CustomSearchParamDef",
    "DateParam",
    "DatePrefix",
    "ExtensionDef",
    "FHIRAuthenticationError",
    "FHIRClient",
    "FHIRConfig",
    "FHIRConnectionError",
    "FHIRError",
    "FHIRProfileDef",
    "FHIRQuery",
    "FHIRQueryBuilder",
    "FHIRResourceNotFoundError",
    "FHIRResourceType",
    "FHIRValidationError",
    "IdentifierSystemDef",
    "IncludeParam",
    "LocaleNotFoundError",
    "LocalePack",
    "LocaleResourceConfig",
    "MatchType",
    "QuantityParam",
    "QueryBuilderError",
    "QueryBuilderValidationError",
    "ReferenceParam",
    "SaludAIError",
    "SortOrder",
    "SortParam",
    "StringParam",
    "SummaryMode",
    "TerminologyCodeNotFoundError",
    "TerminologyConcept",
    "TerminologyConfig",
    "TerminologyDataError",
    "TerminologyError",
    "TerminologyMatch",
    "TerminologyResolver",
    "TerminologySystem",
    "TerminologySystemDef",
    "TokenParam",
    "available_locales",
    "build_fhir_awareness_section",
    "cie10",
    "date_param",
    "load_locale_pack",
    "loinc",
    "quantity",
    "reference",
    "snomed",
    "token",
]
